name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # 匹配vX.Y.Z格式
      - '[0-9]+.[0-9]+.[0-9]+' # 匹配X.Y.Z格式
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+' # 匹配vX.Y.Z-N格式
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+' # 匹配X.Y.Z-N格式

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: linux-aarch64
          # Windows builds
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows-x86_64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: windows-aarch64
          # macOS build (ARM only)
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: macos-aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/ccmk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            Pre-built binaries for ${{ github.ref_name }}
          files: |
            artifacts/linux-x86_64/ccmk
            artifacts/linux-aarch64/ccmk
            artifacts/windows-x86_64/ccmk.exe
            artifacts/windows-aarch64/ccmk.exe
            artifacts/macos-aarch64/ccmk